// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapportiWeb.Server.Data;

#nullable disable

namespace RapportiWeb.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230923150613_controlloCreazioneRapporto2")]
    partial class controlloCreazioneRapporto2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("RapportiWeb.Shared.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CAP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ragioneSociale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("RapportiWeb.Shared.Fad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodRichiesta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodSessione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncaricatoFad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespRic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RifOfferta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fad");
                });

            modelBuilder.Entity("RapportiWeb.Shared.Rapporto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataIntervento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DurataIntervento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCollegamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Incaricato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LuogoIntervento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespInt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespRic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RichiestaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoIntervento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCreazioneRapporto")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Rapporti");
                });

            modelBuilder.Entity("RapportiWeb.Shared.Richiesta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataIntervento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DurataIntervento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiguraProfessionale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Firma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RapportoCreato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsabileRic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipologiaIntervento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("visible")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Richieste");
                });

            modelBuilder.Entity("RapportiWeb.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clienteid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("RapportiWeb.Shared.Rapporto", b =>
                {
                    b.HasOne("RapportiWeb.Shared.Cliente", null)
                        .WithMany("Rapporti")
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapportiWeb.Shared.Richiesta", b =>
                {
                    b.HasOne("RapportiWeb.Shared.Cliente", null)
                        .WithMany("Richieste")
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapportiWeb.Shared.User", b =>
                {
                    b.HasOne("RapportiWeb.Shared.Cliente", null)
                        .WithMany("Utenti")
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RapportiWeb.Shared.Cliente", b =>
                {
                    b.Navigation("Rapporti");

                    b.Navigation("Richieste");

                    b.Navigation("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
